### ISSUE TITLE
Crash when using lower version then 23

### ISSUE THREAD

**Issue by siddhpuraamitr** [mobmead/EasyMPermission#1]
First of all thank you so much for making awesome library, it is so helpful to make reduce code and clean code

I am facing one issue with your nice library

whenever I am using phone lower than v23, application is getting crash

11-03 15:00:42.402 21499-21499/com.mypermissionappexample E/AndroidRuntime: FATAL EXCEPTION: main
11-03 15:00:42.402 21499-21499/com.mypermissionappexample E/AndroidRuntime: Process: com.mypermissionappexample, PID: 21499
11-03 15:00:42.402 21499-21499/com.mypermissionappexample E/AndroidRuntime: java.lang.NoSuchMethodError: com.mypermissionappexample.MainActivity.checkSelfPermission
11-03 15:00:42.402 21499-21499/com.mypermissionappexample E/AndroidRuntime:     at com.mypermissionappexample.MainActivity.isPermissionGranted$(MainActivity.java:14)
11-03 15:00:42.402 21499-21499/com.mypermissionappexample E/AndroidRuntime:     at com.mypermissionappexample.MainActivity.openCamera(MainActivity.java:14)
11-03 15:00:42.402 21499-21499/com.mypermissionappexample E/AndroidRuntime:     at com.mypermissionappexample.MainActivity.access$000(MainActivity.java:15)
11-03 15:00:42.402 21499-21499/com.mypermissionappexample E/AndroidRuntime:     at com.mypermissionappexample.MainActivity$1.onClick(MainActivity.java:28)
11-03 15:00:42.402 21499-21499/com.mypermissionappexample E/AndroidRuntime:     at android.view.View.performClick(View.java:4438)
11-03 15:00:42.402 21499-21499/com.mypermissionappexample E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:18431)
11-03 15:00:42.402 21499-21499/com.mypermissionappexample E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:733)
11-03 15:00:42.402 21499-21499/com.mypermissionappexample E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-03 15:00:42.402 21499-21499/com.mypermissionappexample E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:149)
11-03 15:00:42.402 21499-21499/com.mypermissionappexample E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5045)
11-03 15:00:42.402 21499-21499/com.mypermissionappexample E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-03 15:00:42.402 21499-21499/com.mypermissionappexample E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
11-03 15:00:42.402 21499-21499/com.mypermissionappexample E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
11-03 15:00:42.402 21499-21499/com.mypermissionappexample E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
11-03 15:00:42.402 21499-21499/com.mypermissionappexample E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

Please put condition if below 23 then don't execute code for checking permission 

Thanks,

**Comment by mobmead** [comment]
Thank you for reporting the bug. It has been fixed in 1.0.1 build.
